### ISSUE TITLE
Package summary is missing

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-central#100]
**Description:**
Package summary is missing in the following packages.

health.fhir.r4.aubase410    1.0.7
health.fhir.r4.international401    1.0.2
health.fhir.r4.lkcore010    1.0.0
health.fhir.r4.uscore501    1.2.0

![image](https://github.com/ballerina-platform/ballerina-central/assets/7709843/52265501-5dad-44f2-ae13-a9425fc9054c)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ThishaniLucas** [comment]
Summaries have been added. This will be reflected in the upcoming releases of these packages.

**Comment by sm1990** [comment]
Thank you @ThishaniLucas
