### ISSUE TITLE
Health tool is having incomplete package intro line

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-central#116]
$subject 

<img width="1395" alt="image" src="https://github.com/ballerina-platform/ballerina-central/assets/16300038/2698218b-1e65-4e43-aea9-bbed21ab0671">

**Comment by isuruh15** [comment]
health tools package.md file has the following text;
`This project contains an extension implementation for Ballerina CLI that generates Health artifacts from standard specification files.`[Link](https://github.com/ballerina-platform/fhir-tools/blob/main/ballerina/src/main/resources/health-tool-ballerina/Package.md)
Can this be some issue in the Ballerina central? @azinneera @gayaldassanayake @xlight05

**Comment by gayaldassanayake** [comment]
I pulled the tool and the Package.md seems to be broken the text into 2 separate lines.
<img width="858" alt="image" src="https://github.com/ballerina-platform/ballerina-central/assets/29953428/564988b1-cdfc-4243-846d-e5b26c2bf576">

Need to check if this is happening from the CLI during the bala creation.

**Comment by gayaldassanayake** [comment]
@isuruh15 Ballerina Central only displays the very first line of the description in `Package.md`. However in the case of the health tool, the description is broken into two lines([Link](https://github.com/ballerina-platform/fhir-tools/blob/main/ballerina/src/main/resources/health-tool-ballerina/Package.md?plain=1)) resulting in only the first line to be shown.

All content intended to be in the central description listed in the package search must be in one line.
