### ISSUE TITLE
Builds and Test runs are taking a long time or running indefinitely

### ISSUE THREAD

**Issue by vordimous** [ballerina-platform/ballerina-central#12]
**Description:**
I am executing some ballerina code in a docker container `ballerina/ballerina:2201.2.3` and it seems to be random that some builds/tests runs will be very slow or never finish. I left one to run and stopped it after 4000 seconds. The code is the [hello-world sample](https://ballerina.io/learn/by-example/hello-world/)

![image](https://user-images.githubusercontent.com/3012311/202254541-1a1146de-c404-4c72-acdf-0c9e0902ca2e.png)

**Comment by vordimous** [comment]
one thing to mention is this is running on the mac M1 hardware with the docker flag `--platform linux/amd64 `

**Comment by vordimous** [comment]
I am not seeing a slow down, or at least not as often, when running the builds in github actions

**Comment by anuruddhal** [comment]
Hi @vordimous 
Are you using Rancher Desktop as the Docker VM?

**Comment by vordimous** [comment]
> Hi @vordimous 
> Are you using Rancher Desktop as the Docker host? 
> This is a known issue when using Rancher desktop with a mac m1 chip. 
> As an alternative, can you use [colima](https://github.com/abiosoft/colima) as the docker host?

I was using rancher and downloaded docker to see if it would be better. It is faster but still fails intermittently.

**Comment by anuruddhal** [comment]
Can you try Colima, as it specializes in mac based docker host? 
This issue is due to the m1 chip in mac.

**Comment by vordimous** [comment]
I can try Colima, however, I am also getting slow builds or hangs when running on the local machine.

**Comment by vordimous** [comment]
I tried with colima and still have the hang. it stopped here.
![image](https://user-images.githubusercontent.com/3012311/202572366-a717c99c-5e9e-4b6e-a01f-18e0b19a8c0f.png)

**Comment by vordimous** [comment]
I can't use the `--offline` flag because i am testing the need to download and cache libraries.

**Comment by vordimous** [comment]
Here is a clear indication of pulling from central being the issue:
![image](https://user-images.githubusercontent.com/3012311/202743811-21ffca7e-205c-458b-9252-de5aaac3006c.png)

**Comment by anuruddhal** [comment]
This is expected as there can be issues with network connectivity when using Docker with Mac m1 chip. 

> Users may occasionally experience data drop when a TCP stream is half-closed.

Please reopen the ticket if you encounter an issue in the local build.
