### ISSUE TITLE
Package deprecate labe is appearing randomly when reloading the page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-central#128]
**Description:**

I have a math package with three versions. I did some deprecate/deprecate steps. Finally, I undepreate all the versions. But still, when I reloaded the page from time to time, a deprecated label appeared on some versions. 

Also there is a `null` word appearing when hovering over the deprecate label. 

https://github.com/ballerina-platform/ballerina-central/assets/16300038/804384b6-c74b-4431-b710-24537c734aad

**Comment by anuruddhal** [comment]
The inconsistency in deprecate label is due to page caching.  We will fix the null description.

**Comment by anupama-pathirage** [comment]
Why there is no way to fix it? Btw it is not a correct user experience. IMO, we need to fix it in some way as deprecating a package is a critical action in the package lifecycle, and having inconsistent behavior is making the user super confused.

**Comment by anuruddhal** [comment]
@sm1990 Shall we make the deprecate check render from the client side?
