### ISSUE TITLE
Create mockups for Ballerina Central Authorization Model

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-central#130]
**Description:**
$subject

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
https://www.figma.com/proto/LHQZ5ap3zINJUW7TsxBP4N/central-auth-flow2?type=design&node-id=1-2&t=r0BlRkLInPCHaufx-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2&mode=design
