### ISSUE TITLE
500 Internal Server Error Occurs When Accessing Ballerina Central

### ISSUE THREAD

**Issue by dsplayerX** [ballerina-platform/ballerina-central#138]
**Description:**
When accessing the some documentation pages (for example [aws.s3](https://central.ballerina.io/ballerinax/aws.s3/3.2.0)) on Ballerina Central, a 500 Internal Server Error occurs upon refreshing the page after successful initial loading. The error persists upon refreshing the page.

Refer to the gif below.

![central-500-error](https://github.com/ballerina-platform/ballerina-central/assets/100945633/e8f6e504-4b55-46c8-9244-c08f7902c3c7)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Windows 

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
This was due to the caching of invalid responses in Nginx. This is fixed now.
