### ISSUE TITLE
[Api docs] Fields in included records not clearly distinguishable

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-central#143]
**Description:**
![image](https://github.com/ballerina-platform/ballerina-central/assets/35135122/9dbdfec9-8410-4f08-a058-969574c44b17)

In the above, the first 5 fields are from the included record. And the last 2 fields are overridden by the actual record. But it's hard to identify the fields for a user correctly. It gives the impression of having multiple fields with the same name with different types.

**Comment by anuruddhal** [comment]
Fixed
<img width="1033" alt="Screenshot 2024-06-28 at 12 19 56 PM" src="https://github.com/ballerina-platform/ballerina-central/assets/11031042/c568bf19-897b-4e22-b4c0-00a6b3032b79">
