### ISSUE TITLE
The distribution index JSON cannot be found for released distributions

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-central#151]
**Description:**
The API https://api.central.ballerina.io/2.0/docs/stdlib/2201.9.0 returns a 404 error when attempting to retrieve the distribution index.

**Affected Product Version:**
Ballerina 2201.x.x

**Steps to reproduce:**
curl https://api.central.ballerina.io/2.0/docs/stdlib/2201.9.0

**Related Issues:**

**Comment by anuruddhal** [comment]
This is fixed now
