### ISSUE TITLE
Error when loading API docs for a central package when API docs are not available

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-central#2]
**Description:**
Error when loading API docs for a central package when API docs are not available. 

`ballerinax/mysql.driver/1.3.0` does not have API docs. But, the API docs link for that package is visible and when accessed, fails to load the docs and results in a gateway timeout.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
Fixed now in the revamp central site.
