### ISSUE TITLE
[API Docs] Extended libraries are not appearing in search results of home page serach.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-central#22]
**Description:**

$subect in the lib.ballerina.io landing page.

Try search mysql in landing page search bar.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/16300038/220276176-80ca01fb-fc89-4a8b-836b-f62cdb089f3f.png">

it gives empty results as follows and this is not acceptable.

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/16300038/220276304-ae58bfc6-bb1b-402f-8702-7ba432015ac2.png">

**Comment by anuruddhal** [comment]
This issue is no longer valid after central site revamp.
