### ISSUE TITLE
[API Docs] API docs has very high loading time 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-central#24]
**Description:**
$subject as it takes a considerable amount of time to load the page which is not acceptable. 

Try the URL lib.ballerina.io in a new tab.

**Comment by anupama-pathirage** [comment]
Still experiencing the same slowness, hence reopening the issue. @sm1990

**Comment by anuruddhal** [comment]
Improved performance via https://github.com/wso2-enterprise/ballerina-central/issues/810
