### ISSUE TITLE
Typo in Generated Documentation Code Block: Missing First Letter of the Code

### ISSUE THREAD

**Issue by Ajai-Suvendran** [ballerina-platform/ballerina-central#259]
### Description

In the generated documentation for the ballerinax/financial.iso20022.payment_initiation module on Ballerina Central, there is a typo in the code block where the first letter of a code statement is missing. For example, the word "import" is displayed as "mport," omitting the initial 'i'. However, upon reviewing the module.md file, the code is correctly written, indicating that the issue occurs during the documentation generation process rather than in the source code itself.

<img width="431" alt="Screenshot 2024-10-25 101947" src="https://github.com/user-attachments/assets/31cf44ac-20c8-4744-8b5c-c2b9effbe957">

### Steps to Reproduce

1. Pushed the library package to Ballerina Central with my custom Ballerina organization (ajai21) for testing purposes. 
2. Used ajai21/financial.iso20022 to locate the library in Ballerina Central.

The module.md file I used is given below
[Module.md](https://github.com/user-attachments/files/17515973/Module.md)

### Version

2201.10.1

**Comment by sm1990** [comment]
@Ajai-Suvendran Are you using Windows? If you are, can you change the EOL sequence to `LF`  and try again.
