### ISSUE TITLE
Update the Package.md validation done when pushing a bala to the BC

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-central#260]
### Current Limitation

With the improvement https://github.com/ballerina-platform/ballerina-lang/issues/42981, the BALA files can contain a different file than Package.md. The validation should be updated to support both formats.

### Suggested Improvement

In the new format, the readme file must be taken from the `package.json` file.

E.g. package.json
```json
{
  "organization": "asmaj",
  "name": "doc2",
  "version": "0.1.0",
  "export": [
    "doc2"
  ],
  "ballerina_version": "2201.11.0-SNAPSHOT",
  "implementation_vendor": "WSO2",
  "language_spec_version": "2024R1",
  "platform": "any",
  "graalvmCompatible": true,
  "template": false,
  "readme": "docs/Package.md" // new field
}
```

For old balas, we should keep the current validation; for the new ones, the validation should be updated. To identify if the bala is of the old format or the new one, the bala.json file can be used. The `bala_version` field in the old one is `2.0.0` whereas the one in the new format is `3.0.0`

E.g:
Old bala.json:
```json
{
  "bala_version": "2.0.0",
  "built_by": "WSO2"
}
```

New bala.json
```json
{
  "bala_version": "3.0.0",
  "built_by": "WSO2"
}
```

**Comment by tharindu-nw** [comment]
Still getting the following error: 
```
{"message":"readme record not found"}
```
