### ISSUE TITLE
[API Docs] The `*` seems not necessary when describing type inclusion

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-central#28]
**Description:**

$subject.  Since we say `Type included from` in words, having another `*` in between is not necessary. 

For example see : https://lib.ballerina.io/ballerinax/mssql/1.7.0#CurvePolygonValue

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/16300038/220840768-21b055af-683e-4490-a65d-adcbc6dbe778.png">

**Comment by anuruddhal** [comment]
We have indented included fields as below to make it more distinguishable. Shifted the `*` closer to the type name to make it look similar to the [syntax](https://ballerina.io/learn/by-example/type-inclusion-for-records/).

<img width="1041" alt="Screenshot 2024-06-28 at 10 54 32 AM" src="https://github.com/ballerina-platform/ballerina-central/assets/11031042/4c884944-1c81-487d-8fb3-5c48fa773adc">
