### ISSUE TITLE
Lang libs not loading on API Docs landing page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-central#34]
**Description:**
The language libraries section is not loading on the API Docs landing page as shown below.

### Image

<img width="1680" alt="Screenshot 2023-02-28 at 08 34 50" src="https://user-images.githubusercontent.com/11707273/221743225-b18e0b3a-73d4-4637-93d8-758d894266ce.png">

### Screen recording

https://user-images.githubusercontent.com/11707273/221743162-96ac9510-5b52-483c-aa40-f089968ccbb2.mov

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

<img width="1680" alt="Screenshot 2023-02-28 at 08 34 50" src="https://user-images.githubusercontent.com/11707273/221743171-b52a6095-c44b-4e09-808c-170a1f36e96d.png">

**Comment by anuruddhal** [comment]
This is due to https://github.com/wso2-enterprise/ballerina-registry/issues/1936. Manually triggering the workflow resolved the issue.

**Comment by praneesha** [comment]
This is fixed now as shown below.

<img width="1680" alt="Screenshot 2023-02-28 at 09 14 34" src="https://user-images.githubusercontent.com/11707273/221748249-8928d9d9-3a54-436b-bb5d-e631b91d6796.png">
