### ISSUE TITLE
API Documentation link in mysql.driver page gives 404

### ISSUE THREAD

**Issue by wx-yz** [ballerina-platform/ballerina-central#37]
**Description:**
API Documentation link in [mysql.driver page](https://central.ballerina.io/ballerinax/mysql.driver) gives 404

![image](https://user-images.githubusercontent.com/57770159/223296735-6e277711-af24-47fe-8e7a-7c04f2727816.png)

**Comment by anuruddhal** [comment]
Fixed with new release.
