### ISSUE TITLE
API Documentation for postgresql.driver gives 404

### ISSUE THREAD

**Issue by wx-yz** [ballerina-platform/ballerina-central#38]
**Description:**
API Documentation for [PostgreSQL driver](https://central.ballerina.io/ballerinax/postgresql.driver/1.2.0) gives 404

![image](https://user-images.githubusercontent.com/57770159/223297547-ff8d4bd1-fd0d-4abc-bf97-a34bd58081ab.png)

**Comment by anuruddhal** [comment]
The one you are referring to is deprecated. Please use https://central.ballerina.io/ballerinax/postgresql

**Comment by wx-yz** [comment]
Can we please add a tag/label for all deprecated connectors? This is the first link that shows up when you search 

![image](https://user-images.githubusercontent.com/57770159/224901436-dd814743-c676-4590-82f2-c841b4b99af1.png)

**Comment by anuruddhal** [comment]
This is fixed now.

**Comment by wx-yz** [comment]
@anuruddhal The 404 is fixed yes. However, it doesn't indicated that this is deprecated. Even the github link that's linked to the source repo from https://central.ballerina.io/ballerinax/postgresql.driver/1.2.0 gives no indication to the user that this is deprecated.

Ideally we should have a notice saying this is deprecated, no longer used AND a link to the latest driver the users should use.
