### ISSUE TITLE
API Documentation link broken on several connectors

### ISSUE THREAD

**Issue by wx-yz** [ballerina-platform/ballerina-central#39]
**Description:**
API Documentation link is broken and gives 404 on many connectors in central.ballerina.io

Notice in at least on these (in addition to MySQL and PostgreSQL),
* https://central.ballerina.io/ballerinax/jaeger
* https://central.ballerina.io/ballerinax/choreo

**Comment by anuruddhal** [comment]
The docs are not displayed as there are no public APIs available in these packages.

**Comment by wx-yz** [comment]
@anuruddhal If there are no public APIs available in these packages, then why are we even showing these to the user? It's very confusing to the user. We should only show packages that have a public API. Don't you agree?
