### ISSUE TITLE
Add `search by tag` support for central packages

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-central#42]
**Description:**

$subject. 

Need the ability to search by tag in central.
Also, licking on the tag is directed to the package itself now. Instead, it should list all the packages with the same tag.

**Comment by anuruddhal** [comment]
Tasks

- [ ] Implement an API to Search By Tag https://github.com/wso2-enterprise/ballerina-registry/issues/2001
- [ ] Implement Central UI to display and search packages by tag
