### ISSUE TITLE
Azure Functions and AWS Lambda are missing in `lib.ballerina.io`

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-central#44]
**Description:**
Azure Functions and AWS Lambda packages are missing in the `lib.ballerina.io` landing page.

Need to check and add them.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
Added to new page https://central.ballerina.io/ballerina-library
