### ISSUE TITLE
Check broken links of `lib.ballerina.io`

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-central#45]
**Description:**
Need to run a link checker and fix the broken links in `lib.ballerina.io`.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
lib.ballerina.io is discontinued.
