### ISSUE TITLE
Accessor and resource path are not shown in the function in API docs

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/ballerina-central#49]
**Description:**
Accessor and resource path should be shown in the resource function as it shows the function name for other functions.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sm1990** [comment]
Fixed via https://github.com/wso2-enterprise/ballerina-central/pull/838
