### ISSUE TITLE
http is not shown under Standard library

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-central#5]
**Description:**
`http` is not shown under Standard library in https://lib.ballerina.io/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Production

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sm1990** [comment]
Some related modules of `protobuf` are also missing.

**Comment by anuruddhal** [comment]
This is due to HTTP docs are not packed in the 2201.2.0 distribution. Added a fix for a bug in https://github.com/ballerina-platform/ballerina-lang/pull/37783
