### ISSUE TITLE
`STAN` module not found on `lib.ballerina.io`

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-central#52]
**Description:**
The STAN module is not there on the landing page of the `lib.ballerina.io` and also when searched as shown below.

<img width="1726" alt="Screenshot 2023-04-19 at 12 09 15" src="https://user-images.githubusercontent.com/11707273/232987751-dcc8ccaa-b589-4721-aa3a-95ba76a7510c.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
If the `lib.ballerina.io` search does not include BallerinaX packages, and only a select list of BallerinaX packages are shown on the homepage while others need to be accessed via Ballerina Central, let's mention that on the homepage for a better user experience or add a "See more..." option directing to Central.

**Comment by anuruddhal** [comment]
This is fixed with new release
