### ISSUE TITLE
Add blockquote styles to Ballerina Central

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-central#54]
**Description:**
We need to add the blockquote styles to Ballerina Central. Currently, they are displayed as shown below. For example, see https://central.ballerina.io/ballerinax/stan.

![unnamed](https://user-images.githubusercontent.com/11707273/233692484-4036e355-7107-447a-a0d1-9552f82e82a8.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sm1990** [comment]
Will be fixed in the central revamp. Fixed in dev via https://github.com/wso2-enterprise/ballerina-central/pull/861
