### ISSUE TITLE
Add a deprecation notice to STAN

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-central#57]
## Description
We need to add a deprecation notice to [Ballerinax STAN module](https://github.com/ballerina-platform/module-ballerinax-stan), since the underlying [NATS streaming server](https://github.com/nats-io/nats-streaming-server) is now deprecated by NATS. 

## Suggested assignee(s) (optional)
@praneesha

**Comment by anuruddhal** [comment]
Added https://central.ballerina.io/ballerinax/stan/latest
