### ISSUE TITLE
Documentation for the latest version of http gives a 404

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-central#6]
**Description:**
Documentation for latest version of `http` gives a 404 in API Docs. The issue can be reproduced with both [1] & [2].

[1] https://lib.ballerina.io/ballerina/http/2.4.0
[2] https://lib.ballerina.io/ballerina/http/latest

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Production

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
This is fixed now
