### ISSUE TITLE
Ballerina central copyright remains in 2022 WSO2 

### ISSUE THREAD

**Issue by NilukaSripalim** [ballerina-platform/ballerina-central#72]
Visit : https://central.ballerina.io/
Please refer attached screenshot,

<img width="421" alt="Screenshot 2023-07-04 at 15 02 01" src="https://github.com/ballerina-platform/ballerina-central/assets/39120228/26e4ff4d-ee6f-4965-9239-985b41bbed40">

**Comment by anuruddhal** [comment]
Fixed in the new release.
