### ISSUE TITLE
Deprecate ballerinax/azure_functions package

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-central#75]
**Description:**
In favor of https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/628

Package to be deprecated - https://central.ballerina.io/ballerinax/azure_functions
Deprecation message - Package 'ballerinax/azure_functions' is renamed. Use 'ballerinax/azure.functions' instead. The new version has no breaking changes, and your code should continue to work.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
Done
