### ISSUE TITLE
Deprecation notice of the `serdes` module is not displayed

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-central#76]
**Description:**

The deprecation notice for the `serdes` module is not getting displayed in both Central and API Docs even though they are added in the source files as follows.

**In Ballerina Central**

The deprecation notice is not displayed in https://central.ballerina.io/ballerina/serdes even though the source has it at https://github.com/ballerina-platform/module-ballerina-serdes/blob/main/ballerina/Module.md.

**In API Docs**

The deprecation notice is not displayed in https://lib.ballerina.io/ballerina/serdes/latest even though the source has it at https://github.com/ballerina-platform/module-ballerina-serdes/blob/main/ballerina/Package.md.

They should be displayed correctly as shown in the examples below of the `stan` module.

- https://central.ballerina.io/ballerinax/stan
- https://lib.ballerina.io/ballerinax/stan/latest 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
This is fixed.
