### ISSUE TITLE
[Dev] Remove existing tool packages in the dev central under the tool id, health

### ISSUE THREAD

**Issue by isuruh15** [ballerina-platform/ballerina-central#77]
**Description:**

Since Open Healthcare team is publishing the `health` tool under the `ballerinax` organization, there can't be any other organizations having tools with the same tool id. Hence remove the following tool package from Ballerina dev central.

Organization name: `isurusamaranayake`
Package name: `health`
Versions: all (upto 0.1.10)

**Suggested Labels:**

**Suggested Assignees:**

@xlight05 

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**

N/A

**Comment by xlight05** [comment]
This is done =)
