### ISSUE TITLE
[Central-API Docs Merge] Dashboard & package details page

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-central#78]
**Description:**

- [ ] Add new panel in package detail page to show sub modules and deprecate module buttons.
- [x] Show links to dashboard pages in the sign in drop down menu.
- [x] Pass cookies from home page to dashboard when navigating manually. (tracked in https://github.com/wso2-enterprise/ballerina-central/issues/1003)
- [ ] Fix pending style issues.
- [ ] Show meta data in package detail page for private packages.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
Merged
