### ISSUE TITLE
[Dev] Remove existing tool packages in the dev central under the tool id, health

### ISSUE THREAD

**Issue by isuruh15** [ballerina-platform/ballerina-central#80]
**Description:**

In order to align the version in prod and dev, we need to clear the snapshots versions from the DEV central.

Organization name: `ballerinax`
Package name: `health`
Versions: all (upto 1.0.8)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**

N/A

**Comment by anuruddhal** [comment]
Deleted
