### ISSUE TITLE
Some API docs are not appearing in the search result

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-central#81]
**Description:**
eg: github, graphql, ...

![Screenshot 2023-08-14 at 12 30 06](https://github.com/ballerina-platform/ballerina-central/assets/15815199/3a8da6ce-e8c3-4c41-b30e-e26e8b931b59)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
Fixed with new central release.
