### ISSUE TITLE
0.0.0 default version directs to not found result

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-central#98]
**Description:**
Ideally, this should be redirected to latest
https://central.ballerina.io/ballerina/lang.table/0.0.0

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
Redirecting 0.0.0 to the latest is not correct since 0.0.0 is a valid semver. 

You can access the latest version by.
https://central.ballerina.io/ballerina/lang.table/latest
